import React, { useState, useEffect, useRef } from 'react';
import { DEFAULT_DATA, PASSWORD_HASH } from './constants';
import { ContentData, ViewMode } from './types';
import Editor from './components/Editor';
import WebPreview from './components/WebPreview';
import EmailPreview from './components/EmailPreview';
import AIAssistant from './components/AIAssistant';
import Login from './components/Login';
import HistoryModal from './components/HistoryModal';
import { Layout, Mail, Globe, Code, Copy, Check, Download, AppWindow, Sparkles, ChevronsUpDown, Save, History } from 'lucide-react';
import { generateEmailHTML, generateEML } from './services/emailGenerator';
import { generateSharePointHTML } from './services/sharepointGenerator';

const App: React.FC = () => {
  // Authentication State
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [authChecking, setAuthChecking] = useState(true);

  // App State
  const [data, setData] = useState<ContentData>(DEFAULT_DATA);
  const [activeView, setActiveView] = useState<ViewMode>('web-preview');
  const [copied, setCopied] = useState(false);
  const [isAIMode, setIsAIMode] = useState(false);
  const [isHistoryOpen, setIsHistoryOpen] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  // SharePoint Helper State
  const [sharepointLink, setSharepointLink] = useState('');
  const [iframeHeight, setIframeHeight] = useState(2500);

  // Sidebar Resize State
  const [sidebarWidth, setSidebarWidth] = useState(450);
  const [isResizing, setIsResizing] = useState(false);
  const sidebarRef = useRef<HTMLDivElement>(null);

  const startResizing = React.useCallback(() => {
    setIsResizing(true);
  }, []);

  const stopResizing = React.useCallback(() => {
    setIsResizing(false);
  }, []);

  const resize = React.useCallback(
    (mouseMoveEvent: MouseEvent) => {
      if (isResizing) {
        const newWidth = mouseMoveEvent.clientX;
        if (newWidth > 300 && newWidth < 800) { // Min and Max width constraints
          setSidebarWidth(newWidth);
        }
      }
    },
    [isResizing]
  );

  useEffect(() => {
    window.addEventListener("mousemove", resize);
    window.addEventListener("mouseup", stopResizing);
    return () => {
      window.removeEventListener("mousemove", resize);
      window.removeEventListener("mouseup", stopResizing);
    };
  }, [resize, stopResizing]);

  useEffect(() => {
    const token = localStorage.getItem('auth_token');
    if (token === PASSWORD_HASH) {
      setIsAuthenticated(true);
    }
    setAuthChecking(false);
  }, []);

  const copyCode = (content: string) => {
    navigator.clipboard.writeText(content).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const copyEmailHTML = () => {
    copyCode(generateEmailHTML(data));
  };

  const downloadEML = () => {
    const emlContent = generateEML(data);
    const blob = new Blob([emlContent], { type: 'message/rfc822' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.headerSubtitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.eml`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const downloadASPX = () => {
    const htmlContent = generateSharePointHTML(data);
    // Add BOM (\uFEFF) to strictly enforce UTF-8 in Microsoft products (SharePoint, Excel, etc.)
    const blob = new Blob(['\uFEFF' + htmlContent], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.headerSubtitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.aspx`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const getIframeCode = () => {
    const src = sharepointLink.trim() || 'COLE_SEU_LINK_AQUI';
    return `<iframe src="${src}" width="100%" height="${iframeHeight}" frameborder="0" scrolling="no" style="border:none;"></iframe>`;
  };

  const saveTipToHistory = async (tipData: ContentData = data, manual = false) => {
    setIsSaving(true);
    try {
      const response = await fetch('/api/tips', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: tipData.headerSubtitle || tipData.headerTitle || 'Dica Sem Título',
          content: tipData
        })
      });

      if (manual) {
        if (response.ok) alert('Dica salva no histórico com sucesso! 💾');
        else alert('Erro ao salvar dica.');
      }
    } catch (error) {
      console.error('Error saving tip:', error);
      if (manual) alert('Erro de conexão ao salvar.');
    } finally {
      setIsSaving(false);
    }
  };

  const handleAIGenerate = (newData: ContentData) => {
    setData(newData);
    // Auto-save when generated by AI
    saveTipToHistory(newData, false);
  };

  if (authChecking) {
    return <div className="flex h-screen items-center justify-center bg-gray-100"></div>; // Or a loading spinner
  }

  if (!isAuthenticated) {
    return <Login onLogin={() => setIsAuthenticated(true)} />;
  }

  return (
    <div className="flex h-screen bg-falconi-gray overflow-hidden font-sans">

      {/* AI Assistant Modal */}
      <AIAssistant
        isOpen={isAIMode}
        onClose={() => setIsAIMode(false)}
        onGenerate={handleAIGenerate}
      />

      <HistoryModal
        isOpen={isHistoryOpen}
        onClose={() => setIsHistoryOpen(false)}
        onSelect={(savedData) => setData(savedData)}
      />

      {/* Sidebar / Editor */}
      <aside
        ref={sidebarRef}
        className="relative flex flex-col bg-white border-r border-gray-200 shadow-xl z-10 flex-shrink-0 transition-all duration-75 ease-out"
        style={{ width: sidebarWidth }}
      >
        {/* Drag Handle */}
        <div
          className="absolute right-0 top-0 bottom-0 w-1 bg-transparent hover:bg-falconi-primary/50 cursor-col-resize z-50 transition-colors"
          onMouseDown={startResizing}
          title="Arraste para redimensionar"
        >
          {/* Visual indicator when hovering or resizing */}
          <div className={`h-full w-full ${isResizing ? 'bg-falconi-primary' : ''}`} />
        </div>

        <div className="p-4 bg-falconi-primary text-white flex items-center justify-between shadow-md">
          <div className="flex items-center gap-2">
            <Layout className="text-falconi-secondary" />
            <h1 className="font-bold text-lg tracking-wide">AI Tips <span className="text-falconi-secondary font-light">Generator</span></h1>
          </div>
          <div className="flex gap-1">
            <button onClick={() => saveTipToHistory(data, true)} className="p-1.5 hover:bg-white/20 rounded text-white" title="Salvar agora">
              <Save size={18} />
            </button>
            <button onClick={() => setIsHistoryOpen(true)} className="p-1.5 hover:bg-white/20 rounded text-white" title="Histórico">
              <History size={18} />
            </button>
          </div>
        </div>

        {/* AI Trigger Area */}
        <div className="p-4 border-b border-gray-100 bg-gray-50/50">
          <button
            onClick={() => setIsAIMode(true)}
            className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-falconi-primary to-falconi-primary/80 text-white p-3 rounded-lg font-bold shadow-sm hover:shadow-md transition-all hover:scale-[1.01] group"
          >
            <Sparkles size={18} className="text-falconi-secondary group-hover:animate-spin-slow" fill="currentColor" />
            Criar com Assistente IA
          </button>
          <p className="text-[10px] text-center text-gray-400 mt-2">
            Gere um briefing completo a partir de um texto simples.
          </p>
        </div>

        <div className="flex-1 overflow-y-auto p-4 custom-scrollbar">
          <Editor data={data} onChange={setData} />
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col min-w-0 bg-gray-50">
        {/* Toolbar */}
        <div className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-6 shadow-sm z-0 overflow-x-auto">
          <div className="flex items-center gap-4">
            <div className="flex bg-gray-100 p-1 rounded-lg">
              <button
                onClick={() => setActiveView('web-preview')}
                className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${activeView === 'web-preview' ? 'bg-white text-falconi-primary shadow-sm' : 'text-gray-500 hover:text-gray-900'}`}
              >
                <Globe size={16} /> Web
              </button>
              <button
                onClick={() => setActiveView('email-preview')}
                className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${activeView === 'email-preview' ? 'bg-white text-falconi-primary shadow-sm' : 'text-gray-500 hover:text-gray-900'}`}
              >
                <Mail size={16} /> Outlook
              </button>
              <button
                onClick={() => setActiveView('sharepoint')}
                className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${activeView === 'sharepoint' ? 'bg-white text-falconi-primary shadow-sm' : 'text-gray-500 hover:text-gray-900'}`}
              >
                <AppWindow size={16} /> SharePoint
              </button>
              <button
                onClick={() => setActiveView('export')}
                className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all whitespace-nowrap ${activeView === 'export' ? 'bg-white text-falconi-primary shadow-sm' : 'text-gray-500 hover:text-gray-900'}`}
              >
                <Code size={16} /> Obter Código
              </button>
            </div>

            {activeView === 'email-preview' && (
              <button
                onClick={downloadEML}
                className="flex items-center gap-2 px-4 py-2 bg-falconi-secondary text-falconi-primary rounded-md text-sm font-bold hover:bg-opacity-90 transition shadow-sm animate-in fade-in whitespace-nowrap"
              >
                <Download size={16} /> Baixar .eml
              </button>
            )}
          </div>
        </div>

        {/* Viewport */}
        <div className="flex-1 overflow-y-auto relative bg-gray-100">
          {activeView === 'web-preview' && <WebPreview data={data} />}
          {activeView === 'email-preview' && <EmailPreview data={data} />}

          {activeView === 'sharepoint' && (
            <div className="p-8 max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-8 h-full">
              {/* Instructions Column */}
              <div className="bg-white rounded-lg shadow-lg border border-gray-200 p-6 flex flex-col">
                <h2 className="text-2xl font-bold text-falconi-primary mb-6 flex items-center gap-2">
                  <AppWindow /> Assistente de Publicação
                </h2>

                <div className="space-y-8 text-gray-600 flex-1 overflow-y-auto pr-2 custom-scrollbar">

                  {/* Step 1 */}
                  <div className="relative pl-8 border-l-2 border-falconi-gray">
                    <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-falconi-secondary border-2 border-white"></div>
                    <h3 className="font-bold text-gray-800 mb-2">1. Baixe o Arquivo .aspx</h3>
                    <p className="text-sm mb-3">O código foi corrigido para evitar erros de acentuação (UTF-8).</p>
                    <button
                      onClick={downloadASPX}
                      className="flex items-center gap-2 px-4 py-2 bg-falconi-primary text-white rounded-md text-sm font-bold hover:bg-opacity-90 transition shadow-sm"
                    >
                      <Download size={16} /> Baixar Arquivo .aspx
                    </button>
                  </div>

                  {/* Step 2 */}
                  <div className="relative pl-8 border-l-2 border-falconi-gray">
                    <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-gray-300 border-2 border-white"></div>
                    <h3 className="font-bold text-gray-800 mb-2">2. Faça Upload no SharePoint</h3>
                    <p className="text-sm mb-2">Suba o arquivo na biblioteca "Documentos" do site e copie o link direto dele.</p>
                  </div>

                  {/* Step 3 */}
                  <div className="relative pl-8 border-l-2 border-falconi-gray">
                    <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-gray-300 border-2 border-white"></div>
                    <h3 className="font-bold text-gray-800 mb-2">3. Cole o Link Direto</h3>
                    <input
                      type="text"
                      placeholder="https://..."
                      value={sharepointLink}
                      onChange={(e) => setSharepointLink(e.target.value)}
                      className="w-full p-3 border border-gray-300 rounded focus:ring-2 focus:ring-falconi-primary text-sm font-mono"
                    />
                  </div>

                  {/* Step 4 */}
                  <div className="relative pl-8 border-l-2 border-transparent">
                    <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-gray-300 border-2 border-white"></div>
                    <h3 className="font-bold text-gray-800 mb-2">4. Ajuste e Copie o Código</h3>
                    <p className="text-sm mb-3">Ajuste a altura para remover a barra de rolagem.</p>

                    <div className="flex items-center gap-4 mb-4 bg-gray-50 p-3 rounded border border-gray-200">
                      <label className="text-sm font-bold text-gray-600 flex items-center gap-2">
                        <ChevronsUpDown size={16} /> Altura (px):
                      </label>
                      <input
                        type="number"
                        value={iframeHeight}
                        onChange={(e) => setIframeHeight(Number(e.target.value))}
                        className="w-24 p-1 border border-gray-300 rounded text-center font-mono"
                      />
                      <span className="text-xs text-gray-500">Aumente se aparecer rolagem</span>
                    </div>
                  </div>

                </div>
              </div>

              {/* Code Column */}
              <div className="bg-white rounded-lg shadow-lg border border-gray-200 flex flex-col h-[600px] lg:h-auto">
                <div className="p-4 border-b bg-gray-50 flex justify-between items-center">
                  <h3 className="font-bold text-gray-700">Código de Inserção</h3>
                  <button
                    onClick={() => copyCode(getIframeCode())}
                    className={`flex items-center gap-2 px-4 py-2 rounded text-sm font-bold transition-colors ${copied ? 'bg-green-100 text-green-700' : 'bg-falconi-primary text-white hover:bg-opacity-90'}`}
                  >
                    {copied ? <Check size={16} /> : <Copy size={16} />}
                    {copied ? 'Copiado!' : 'Copiar'}
                  </button>
                </div>
                <div className="flex-1 bg-gray-900 p-4 overflow-auto custom-scrollbar relative">
                  <div className="text-gray-400 text-xs mb-2 font-sans border-b border-gray-700 pb-2">
                    Cole na Web Part "Inserir" (&lt;/&gt;):
                  </div>
                  <code className="text-green-400 text-sm font-mono whitespace-pre-wrap break-all block">
                    {getIframeCode()}
                  </code>
                </div>
              </div>
            </div>
          )}

          {activeView === 'export' && (
            <div className="p-8 max-w-4xl mx-auto">
              <div className="bg-white rounded-lg shadow-lg border border-gray-200 overflow-hidden">
                <div className="p-4 border-b bg-gray-50 flex justify-between items-center">
                  <h3 className="font-bold text-gray-700">HTML para E-mail Marketing</h3>
                  <div className="flex gap-2">
                    <button
                      onClick={downloadEML}
                      className="flex items-center gap-2 px-4 py-2 rounded text-sm font-bold bg-falconi-secondary text-falconi-primary hover:bg-opacity-90"
                    >
                      <Download size={16} /> Baixar .eml
                    </button>
                    <button
                      onClick={copyEmailHTML}
                      className={`flex items-center gap-2 px-4 py-2 rounded text-sm font-bold transition-colors ${copied ? 'bg-green-100 text-green-700' : 'bg-falconi-primary text-white hover:bg-opacity-90'}`}
                    >
                      {copied ? <Check size={16} /> : <Copy size={16} />}
                      {copied ? 'Copiado!' : 'Copiar HTML'}
                    </button>
                  </div>
                </div>
                <div className="p-6 bg-yellow-50 border-b border-yellow-100 text-yellow-800 text-sm">
                  <strong>Atenção:</strong> Para E-mail Marketing, lembre-se de hospedar as imagens em um servidor público.
                </div>
                <div className="p-4 bg-gray-900 overflow-auto h-[500px]">
                  <code className="text-green-400 text-xs font-mono whitespace-pre">
                    {generateEmailHTML(data)}
                  </code>
                </div>
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default App;